CREATE TABLE [dbo].[SocialLinks]
(
	[Id] INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[PersonId] INT NULL FOREIGN KEY REFERENCES Persons(Id),
	CONSTRAINT fk_person_id FOREIGN KEY(PersonId) REFERENCES Persons(Id) ON DELETE CASCADE,
	[Name] NVARCHAR(MAX),
	[Link] NVARCHAR(MAX)
)
